const kayakDomains = {
    "argentina": "kayak.com.ar",
    "australia": "kayak.com.au",
    "austria": "at.kayak.com",
    "belgium": "be.kayak.com",
    "bolivia": "kayak.bo",
    "brazil": "kayak.com.br",
    "canada": "ca.kayak.com",
    "catalonia": "kayak.cat",
    "chile": "kayak.cl",
    "china": "cn.kayak.com",
    "colombia": "kayak.com.co",
    "costa rica": "kayak.co.cr",
    "czech republic": "cz.kayak.com",
    "denmark": "kayak.dk",
    "dominican republic ": "kayak.com.do",
    "ecuador": "kayak.com.ec",
    "el salvador": "kayak.com.sv",
    "estonia": "momondo.ee",
    "finland": "fi.kayak.com",
    "france": "kayak.fr",
    "germany": "kayak.de",
    "greece": "gr.kayak.com",
    "guatemala": "kayak.com.gt",
    "honduras": "kayak.com.hn",
    "hong kong": "kayak.com.hk",
    "india": "kayak.co.in",
    "indonesia": "kayak.co.id",
    "ireland": "kayak.ie",
    "israel": "il.kayak.com",
    "italy": "kayak.it",
    "japan": "kayak.co.jp",
    "malaysia": "kayak.com.my",
    "mexico": "kayak.com.mx",
    "netherlands": "kayak.nl",
    "new zealand": "nz.kayak.com",
    "nicaragua": "kayak.com.ni",
    "norway": "kayak.no",
    "panama": "kayak.com.pa",
    "paraguay": "kayak.com.py",
    "peru": "kayak.com.pe",
    "philippines": "kayak.com.ph",
    "poland": "kayak.pl",
    "portugal": "kayak.pt",
    "puerto rico": "kayak.com.pr",
    "qatar": "cheapflights.qa",
    "romania": "ro.kayak.com",
    "saudi arabia": "en.kayak.sa",
    "singapore": "kayak.sg",
    "south africa": "za.kayak.com",
    "south korea": "kayak.co.kr",
    "spain": "kayak.es",
    "sweden": "kayak.se",
    "switzerland": "kayak.ch",
    "taiwan": "tw.kayak.com",
    "thailand": "kayak.co.th",
    "turkey": "kayak.com.tr",
    "ukraine": "ua.kayak.com",
    "united arab emirates": "kayak.ae",
    "united kingdom": "kayak.co.uk",
    "united states": "kayak.com",
    "uruguay": "kayak.com.uy",
    "venezuela": "kayak.co.ve",
    "vietnam": "vn.kayak.com"
}

export default kayakDomains;
